version: '3.7'

services:
  retyp-api:
    container_name: retyp-api
    hostname: retyp-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: retyp-api:latest
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    depends_on: 
      - retyp-redis
    command: npm run dev

  retyp-redis:
    container_name: retyp-redis
    hostname: retyp-redis
    image: redis:5.0.7-alpine3.11
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}